//
//	Last Modified: $Date: 2010-07-20 09:48:11 $
//
//	$Log: TAPISTR.H,v $
//	Revision 1.2  2010-07-20 09:48:11  lgrave
//	corrected windows crlf to unix lf
//

//	Revision 1.1  2010-07-19 23:40:41  lgrave

//	1st version added to cvs

//
//

// TAPISTR.CPP
//
// TAPI application class library v1.00
// This file contains all the ASCII strings for the library
// Original Copyright © 1995-2004 JulMar Entertainment Technology, Inc. All rights reserved.
//
// "This program is free software; you can redistribute it and/or modify it under the terms of 
// the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
// even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General 
// Public License for more details.
//
// You should have received a copy of the GNU General Public License along with this program; if not, write 
// to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. 
// Or, contact: JulMar Technology, Inc. at: info@julmar.com." 
//

#ifndef INCL_TAPI_STRINGS_

#define TAPISTR_NOLINENAME      _T("Line unnamed")
#define TAPISTR_NOLINE          _T("Line unavailable")
#define TAPISTR_NOPHONENAME     _T("Phone unnamed")
#define TAPISTR_NOPHONE         _T("Phone unavailable")
#define TAPISTR_NOADDRNAME      _T("Address unknown")
#define TAPISTR_NOPROVIDERINFO  _T("Provider unknown")
#define TAPISTR_SWITCHUNKNOWN   _T("Switch information unavailable")
#define TAPISTR_LCS_IDLE        _T("Idle")
#define TAPISTR_LCS_OFFERING	_T("Offering")
#define TAPISTR_LCS_ACCEPTED	_T("Accepted")
#define TAPISTR_LCS_DIALTONE	_T("Dialtone")
#define TAPISTR_LCS_DIALING		_T("Dialing")
#define TAPISTR_LCS_RINGBACK	_T("Ringback")
#define TAPISTR_LCS_BUSY		_T("Busy")
#define TAPISTR_LCS_SPECIALINFO	_T("SpecialInfo")
#define TAPISTR_LCS_CONNECTED	_T("Connected")
#define TAPISTR_LCS_PROCEEDING	_T("Proceeding")
#define TAPISTR_LCS_ONHOLD		_T("On Hold")
#define TAPISTR_LCS_CONFERENCED _T("Conferenced")
#define TAPISTR_LCS_ONHOLDPENDCONF _T("On Hold Pending Conference")
#define TAPISTR_LCS_ONHOLDPENDXFER _T("On Hold Pending Transfer")
#define TAPISTR_LCS_DISCONNECTED _T("Disconnected")
#define TAPISTR_LCS_UNKNOWN		_T("Unknown")

#endif // INCL_TAPI_STRINGS_
